// ── ICON-LIBRARY ────────────────────────────────────────────
// Catálogo grande de iconos FontAwesome organizados por grupos,
// con palabras clave (incluye español) para el buscador.
// Cada icono: { c: claseFA, k: 'keywords para buscar' }

export const ICON_GROUPS = [
  {
    id: 'finanzas', label: 'Finanzas', icon: 'fa-solid fa-wallet',
    icons: [
      { c: 'fa-solid fa-wallet', k: 'billetera wallet cartera dinero' },
      { c: 'fa-solid fa-money-bill-wave', k: 'dinero efectivo billete cash plata' },
      { c: 'fa-solid fa-money-bill-1', k: 'dinero billete cash' },
      { c: 'fa-solid fa-money-bills', k: 'dinero billetes fajo cash' },
      { c: 'fa-solid fa-money-bill-trend-up', k: 'ganancia dinero inversion subida' },
      { c: 'fa-solid fa-money-check-dollar', k: 'cheque pago dinero nomina' },
      { c: 'fa-solid fa-coins', k: 'monedas coins dinero ahorro' },
      { c: 'fa-solid fa-piggy-bank', k: 'ahorro cerdito hucha piggy' },
      { c: 'fa-solid fa-credit-card', k: 'tarjeta credito card debito' },
      { c: 'fa-solid fa-building-columns', k: 'banco banco columnas institucion' },
      { c: 'fa-solid fa-landmark', k: 'banco gobierno institucion' },
      { c: 'fa-solid fa-hand-holding-dollar', k: 'prestamo deuda dinero pago dolar' },
      { c: 'fa-solid fa-sack-dollar', k: 'saco dinero dolar bolsa' },
      { c: 'fa-solid fa-dollar-sign', k: 'dolar dinero peso signo' },
      { c: 'fa-solid fa-euro-sign', k: 'euro dinero moneda' },
      { c: 'fa-solid fa-sterling-sign', k: 'libra dinero moneda' },
      { c: 'fa-solid fa-peso-sign', k: 'peso dinero moneda' },
      { c: 'fa-solid fa-yen-sign', k: 'yen dinero moneda japon' },
      { c: 'fa-solid fa-bitcoin-sign', k: 'bitcoin cripto crypto moneda' },
      { c: 'fa-brands fa-bitcoin', k: 'bitcoin cripto crypto' },
      { c: 'fa-brands fa-ethereum', k: 'ethereum cripto crypto eth' },
      { c: 'fa-solid fa-chart-line', k: 'grafica inversion bolsa subida trading' },
      { c: 'fa-solid fa-chart-pie', k: 'grafica presupuesto porcentaje pie' },
      { c: 'fa-solid fa-chart-simple', k: 'grafica barras estadistica' },
      { c: 'fa-solid fa-chart-column', k: 'grafica columnas estadistica' },
      { c: 'fa-solid fa-arrow-trend-up', k: 'subida ganancia tendencia' },
      { c: 'fa-solid fa-arrow-trend-down', k: 'bajada perdida tendencia' },
      { c: 'fa-solid fa-percent', k: 'porcentaje interes descuento' },
      { c: 'fa-solid fa-receipt', k: 'recibo factura ticket comprobante' },
      { c: 'fa-solid fa-file-invoice-dollar', k: 'factura recibo pago cuenta' },
      { c: 'fa-solid fa-cash-register', k: 'caja registradora venta' },
      { c: 'fa-solid fa-vault', k: 'boveda caja fuerte seguro ahorro' },
      { c: 'fa-solid fa-scale-balanced', k: 'balance equilibrio justicia' },
      { c: 'fa-brands fa-paypal', k: 'paypal pago online' },
      { c: 'fa-brands fa-cc-visa', k: 'visa tarjeta pago' },
      { c: 'fa-brands fa-cc-mastercard', k: 'mastercard tarjeta pago' },
      { c: 'fa-brands fa-cc-paypal', k: 'paypal tarjeta pago' },
      { c: 'fa-brands fa-stripe', k: 'stripe pago online' },
      { c: 'fa-brands fa-amazon-pay', k: 'amazon pago online' },
      { c: 'fa-brands fa-google-pay', k: 'google pay pago' },
      { c: 'fa-brands fa-apple-pay', k: 'apple pay pago' },
    ],
  },
  {
    id: 'trabajo', label: 'Trabajo y negocios', icon: 'fa-solid fa-briefcase',
    icons: [
      { c: 'fa-solid fa-briefcase', k: 'trabajo maletin negocio empleo' },
      { c: 'fa-solid fa-building', k: 'edificio empresa oficina negocio' },
      { c: 'fa-solid fa-building-user', k: 'oficina empresa empleado' },
      { c: 'fa-solid fa-store', k: 'tienda negocio comercio' },
      { c: 'fa-solid fa-shop', k: 'tienda comercio local' },
      { c: 'fa-solid fa-industry', k: 'fabrica industria empresa' },
      { c: 'fa-solid fa-warehouse', k: 'bodega almacen inventario' },
      { c: 'fa-solid fa-handshake', k: 'acuerdo trato negocio socio' },
      { c: 'fa-solid fa-user-tie', k: 'ejecutivo jefe trabajo profesional' },
      { c: 'fa-solid fa-people-group', k: 'equipo grupo personas trabajo' },
      { c: 'fa-solid fa-calendar-days', k: 'calendario fecha agenda' },
      { c: 'fa-solid fa-clock', k: 'reloj tiempo hora horario' },
      { c: 'fa-solid fa-business-time', k: 'trabajo tiempo horario reloj' },
      { c: 'fa-solid fa-envelope', k: 'correo email mensaje' },
      { c: 'fa-solid fa-phone', k: 'telefono llamada contacto' },
      { c: 'fa-solid fa-print', k: 'impresora oficina documento' },
      { c: 'fa-solid fa-paperclip', k: 'clip adjunto oficina' },
      { c: 'fa-solid fa-folder', k: 'carpeta archivo documento' },
      { c: 'fa-solid fa-folder-open', k: 'carpeta abierta archivo' },
      { c: 'fa-solid fa-clipboard', k: 'portapapeles tarea lista' },
      { c: 'fa-solid fa-clipboard-check', k: 'tarea completada lista' },
      { c: 'fa-solid fa-bullhorn', k: 'anuncio marketing publicidad' },
      { c: 'fa-solid fa-lightbulb', k: 'idea bombilla creatividad' },
      { c: 'fa-solid fa-rocket', k: 'cohete lanzamiento startup' },
      { c: 'fa-solid fa-trophy', k: 'trofeo premio logro ganar' },
      { c: 'fa-solid fa-medal', k: 'medalla premio logro' },
      { c: 'fa-solid fa-signature', k: 'firma contrato documento' },
      { c: 'fa-solid fa-stamp', k: 'sello aprobado documento' },
      { c: 'fa-solid fa-scale-unbalanced', k: 'legal abogado justicia' },
      { c: 'fa-solid fa-gavel', k: 'martillo juez legal subasta' },
    ],
  },
  {
    id: 'codigo', label: 'Desarrollo y código', icon: 'fa-solid fa-code',
    icons: [
      { c: 'fa-solid fa-code', k: 'codigo programar desarrollo software' },
      { c: 'fa-solid fa-laptop-code', k: 'laptop codigo programar desarrollador' },
      { c: 'fa-solid fa-terminal', k: 'terminal consola comando codigo' },
      { c: 'fa-solid fa-code-branch', k: 'git rama branch version' },
      { c: 'fa-solid fa-code-commit', k: 'git commit version' },
      { c: 'fa-solid fa-code-pull-request', k: 'git pull request merge' },
      { c: 'fa-solid fa-bug', k: 'bug error insecto debug' },
      { c: 'fa-solid fa-bug-slash', k: 'sin bug arreglado fix' },
      { c: 'fa-solid fa-database', k: 'base datos database sql' },
      { c: 'fa-solid fa-server', k: 'servidor server hosting' },
      { c: 'fa-solid fa-microchip', k: 'chip procesador hardware cpu' },
      { c: 'fa-solid fa-laptop', k: 'laptop computadora portatil' },
      { c: 'fa-solid fa-desktop', k: 'computadora pc monitor escritorio' },
      { c: 'fa-solid fa-keyboard', k: 'teclado escribir codigo' },
      { c: 'fa-solid fa-mouse', k: 'raton mouse computadora' },
      { c: 'fa-solid fa-sitemap', k: 'estructura arbol arquitectura' },
      { c: 'fa-solid fa-cloud', k: 'nube cloud servidor' },
      { c: 'fa-solid fa-cloud-arrow-up', k: 'subir nube upload backup' },
      { c: 'fa-solid fa-robot', k: 'robot ia inteligencia bot' },
      { c: 'fa-solid fa-gears', k: 'engranajes configuracion ajustes' },
      { c: 'fa-solid fa-file-code', k: 'archivo codigo script' },
      { c: 'fa-solid fa-window-maximize', k: 'ventana app aplicacion' },
      { c: 'fa-brands fa-github', k: 'github git repositorio codigo' },
      { c: 'fa-brands fa-gitlab', k: 'gitlab git repositorio' },
      { c: 'fa-brands fa-js', k: 'javascript js codigo' },
      { c: 'fa-brands fa-python', k: 'python codigo lenguaje' },
      { c: 'fa-brands fa-react', k: 'react javascript frontend' },
      { c: 'fa-brands fa-vuejs', k: 'vue javascript frontend' },
      { c: 'fa-brands fa-angular', k: 'angular javascript frontend' },
      { c: 'fa-brands fa-node-js', k: 'node javascript backend' },
      { c: 'fa-brands fa-html5', k: 'html web frontend' },
      { c: 'fa-brands fa-css3-alt', k: 'css web estilos' },
      { c: 'fa-brands fa-java', k: 'java codigo lenguaje' },
      { c: 'fa-brands fa-php', k: 'php codigo lenguaje' },
      { c: 'fa-brands fa-docker', k: 'docker contenedor devops' },
      { c: 'fa-brands fa-aws', k: 'aws amazon nube servidor' },
      { c: 'fa-brands fa-figma', k: 'figma diseno ui' },
      { c: 'fa-brands fa-wordpress', k: 'wordpress web cms' },
    ],
  },
  {
    id: 'comida', label: 'Comida y bebida', icon: 'fa-solid fa-utensils',
    icons: [
      { c: 'fa-solid fa-utensils', k: 'comida restaurante cubiertos comer' },
      { c: 'fa-solid fa-burger', k: 'hamburguesa comida rapida burger' },
      { c: 'fa-solid fa-pizza-slice', k: 'pizza comida italiana' },
      { c: 'fa-solid fa-hotdog', k: 'perro caliente hotdog comida' },
      { c: 'fa-solid fa-drumstick-bite', k: 'pollo carne comida' },
      { c: 'fa-solid fa-bacon', k: 'tocino desayuno comida' },
      { c: 'fa-solid fa-fish', k: 'pescado comida mar' },
      { c: 'fa-solid fa-shrimp', k: 'camaron mariscos comida mar' },
      { c: 'fa-solid fa-egg', k: 'huevo desayuno comida' },
      { c: 'fa-solid fa-cheese', k: 'queso comida' },
      { c: 'fa-solid fa-bread-slice', k: 'pan comida panaderia' },
      { c: 'fa-solid fa-ice-cream', k: 'helado postre dulce' },
      { c: 'fa-solid fa-cookie-bite', k: 'galleta dulce postre' },
      { c: 'fa-solid fa-cake-candles', k: 'pastel torta cumpleanos' },
      { c: 'fa-solid fa-candy-cane', k: 'dulce caramelo baston' },
      { c: 'fa-solid fa-apple-whole', k: 'manzana fruta comida sana' },
      { c: 'fa-solid fa-carrot', k: 'zanahoria verdura vegetal' },
      { c: 'fa-solid fa-lemon', k: 'limon fruta citrico' },
      { c: 'fa-solid fa-pepper-hot', k: 'chile picante aji comida' },
      { c: 'fa-solid fa-bowl-food', k: 'plato comida tazon' },
      { c: 'fa-solid fa-bowl-rice', k: 'arroz comida plato' },
      { c: 'fa-solid fa-plate-wheat', k: 'plato comida trigo' },
      { c: 'fa-solid fa-mug-hot', k: 'cafe bebida caliente te' },
      { c: 'fa-solid fa-mug-saucer', k: 'cafe taza bebida' },
      { c: 'fa-solid fa-wine-glass', k: 'vino copa bebida alcohol' },
      { c: 'fa-solid fa-wine-bottle', k: 'vino botella alcohol' },
      { c: 'fa-solid fa-beer-mug-empty', k: 'cerveza bebida alcohol' },
      { c: 'fa-solid fa-martini-glass-citrus', k: 'coctel bebida trago' },
      { c: 'fa-solid fa-bottle-water', k: 'agua botella bebida' },
      { c: 'fa-solid fa-champagne-glasses', k: 'champan brindis celebracion' },
      { c: 'fa-solid fa-jar', k: 'frasco tarro conserva' },
      { c: 'fa-solid fa-seedling', k: 'organico vegetal planta' },
    ],
  },
  {
    id: 'compras', label: 'Compras y tiendas', icon: 'fa-solid fa-bag-shopping',
    icons: [
      { c: 'fa-solid fa-bag-shopping', k: 'compras bolsa shopping tienda' },
      { c: 'fa-solid fa-cart-shopping', k: 'carrito compras supermercado' },
      { c: 'fa-solid fa-cart-plus', k: 'agregar carrito compra' },
      { c: 'fa-solid fa-basket-shopping', k: 'canasta compras supermercado' },
      { c: 'fa-solid fa-store', k: 'tienda comercio local' },
      { c: 'fa-solid fa-shop', k: 'tienda comercio negocio' },
      { c: 'fa-solid fa-tag', k: 'etiqueta precio oferta compra' },
      { c: 'fa-solid fa-tags', k: 'etiquetas precios ofertas' },
      { c: 'fa-solid fa-gift', k: 'regalo obsequio compra' },
      { c: 'fa-solid fa-gifts', k: 'regalos obsequios navidad' },
      { c: 'fa-solid fa-box', k: 'caja paquete producto' },
      { c: 'fa-solid fa-boxes-stacked', k: 'cajas inventario stock' },
      { c: 'fa-solid fa-truck-fast', k: 'envio entrega delivery rapido' },
      { c: 'fa-solid fa-barcode', k: 'codigo barras producto compra' },
      { c: 'fa-solid fa-qrcode', k: 'codigo qr pago compra' },
      { c: 'fa-brands fa-amazon', k: 'amazon compras online tienda' },
      { c: 'fa-brands fa-shopify', k: 'shopify tienda online' },
      { c: 'fa-brands fa-ebay', k: 'ebay compras online' },
    ],
  },
  {
    id: 'ropa', label: 'Ropa y moda', icon: 'fa-solid fa-shirt',
    icons: [
      { c: 'fa-solid fa-shirt', k: 'ropa camisa camiseta vestir moda' },
      { c: 'fa-solid fa-vest', k: 'chaleco ropa vestir' },
      { c: 'fa-solid fa-vest-patches', k: 'chaleco ropa parches' },
      { c: 'fa-solid fa-socks', k: 'medias calcetines ropa' },
      { c: 'fa-solid fa-mitten', k: 'guante mitones frio ropa' },
      { c: 'fa-solid fa-shoe-prints', k: 'zapatos calzado ropa huella' },
      { c: 'fa-solid fa-hat-cowboy', k: 'sombrero vaquero ropa' },
      { c: 'fa-solid fa-hat-wizard', k: 'sombrero mago gorro' },
      { c: 'fa-solid fa-graduation-cap', k: 'gorro graduacion sombrero' },
      { c: 'fa-solid fa-user-tie', k: 'corbata traje ropa formal' },
      { c: 'fa-solid fa-glasses', k: 'gafas lentes accesorio sol' },
      { c: 'fa-solid fa-gem', k: 'joya diamante lujo' },
      { c: 'fa-solid fa-ring', k: 'anillo joya lujo' },
      { c: 'fa-solid fa-crown', k: 'corona rey lujo premium' },
      { c: 'fa-solid fa-clock', k: 'reloj accesorio' },
      { c: 'fa-solid fa-spray-can-sparkles', k: 'perfume belleza aseo' },
      { c: 'fa-solid fa-wand-magic-sparkles', k: 'belleza magia brillo' },
      { c: 'fa-solid fa-scissors', k: 'tijeras corte peluqueria' },
      { c: 'fa-solid fa-baby', k: 'ropa bebe' },
      { c: 'fa-brands fa-nike', k: 'nike ropa deportiva marca' },
    ],
  },
  {
    id: 'viajes', label: 'Viajes y transporte', icon: 'fa-solid fa-plane',
    icons: [
      { c: 'fa-solid fa-plane', k: 'avion viaje vuelo aeropuerto' },
      { c: 'fa-solid fa-plane-departure', k: 'avion despegue viaje vuelo' },
      { c: 'fa-solid fa-plane-arrival', k: 'avion aterrizaje llegada' },
      { c: 'fa-solid fa-car', k: 'carro auto coche vehiculo' },
      { c: 'fa-solid fa-car-side', k: 'carro auto coche' },
      { c: 'fa-solid fa-taxi', k: 'taxi transporte carro' },
      { c: 'fa-solid fa-bus', k: 'bus autobus transporte' },
      { c: 'fa-solid fa-van-shuttle', k: 'furgoneta van transporte' },
      { c: 'fa-solid fa-train', k: 'tren transporte viaje' },
      { c: 'fa-solid fa-train-subway', k: 'metro subterraneo transporte' },
      { c: 'fa-solid fa-train-tram', k: 'tranvia transporte' },
      { c: 'fa-solid fa-motorcycle', k: 'moto motocicleta transporte' },
      { c: 'fa-solid fa-bicycle', k: 'bicicleta bici transporte' },
      { c: 'fa-solid fa-truck', k: 'camion carga transporte envio' },
      { c: 'fa-solid fa-ship', k: 'barco crucero viaje mar' },
      { c: 'fa-solid fa-sailboat', k: 'velero barco mar' },
      { c: 'fa-solid fa-helicopter', k: 'helicoptero transporte aire' },
      { c: 'fa-solid fa-gas-pump', k: 'gasolina combustible carro' },
      { c: 'fa-solid fa-charging-station', k: 'carga electrico auto estacion' },
      { c: 'fa-solid fa-road', k: 'carretera camino viaje' },
      { c: 'fa-solid fa-map-location-dot', k: 'mapa ubicacion viaje gps' },
      { c: 'fa-solid fa-location-dot', k: 'ubicacion pin mapa lugar' },
      { c: 'fa-solid fa-compass', k: 'brujula direccion viaje' },
      { c: 'fa-solid fa-suitcase-rolling', k: 'maleta viaje equipaje' },
      { c: 'fa-solid fa-suitcase', k: 'maleta equipaje viaje' },
      { c: 'fa-solid fa-passport', k: 'pasaporte viaje documento' },
      { c: 'fa-solid fa-hotel', k: 'hotel hospedaje viaje' },
      { c: 'fa-solid fa-bed', k: 'cama hotel hospedaje' },
      { c: 'fa-solid fa-umbrella-beach', k: 'playa vacaciones descanso' },
      { c: 'fa-solid fa-mountain-sun', k: 'montana naturaleza viaje' },
      { c: 'fa-solid fa-earth-americas', k: 'mundo tierra global viaje' },
      { c: 'fa-solid fa-square-parking', k: 'parqueadero estacionamiento auto' },
      { c: 'fa-brands fa-uber', k: 'uber transporte taxi' },
      { c: 'fa-brands fa-airbnb', k: 'airbnb hospedaje viaje' },
    ],
  },
  {
    id: 'casa', label: 'Hogar y servicios', icon: 'fa-solid fa-house',
    icons: [
      { c: 'fa-solid fa-house', k: 'casa hogar vivienda arriendo' },
      { c: 'fa-solid fa-house-chimney', k: 'casa hogar vivienda' },
      { c: 'fa-solid fa-house-user', k: 'casa hogar familia' },
      { c: 'fa-solid fa-key', k: 'llave casa arriendo alquiler' },
      { c: 'fa-solid fa-couch', k: 'sofa mueble hogar sala' },
      { c: 'fa-solid fa-chair', k: 'silla mueble hogar' },
      { c: 'fa-solid fa-bed', k: 'cama dormitorio hogar' },
      { c: 'fa-solid fa-bath', k: 'bano tina hogar' },
      { c: 'fa-solid fa-toilet', k: 'bano inodoro hogar' },
      { c: 'fa-solid fa-shower', k: 'ducha bano hogar' },
      { c: 'fa-solid fa-faucet', k: 'agua grifo servicio hogar' },
      { c: 'fa-solid fa-faucet-drip', k: 'agua goteo servicio' },
      { c: 'fa-solid fa-bolt', k: 'luz electricidad energia servicio' },
      { c: 'fa-solid fa-plug', k: 'enchufe electricidad energia' },
      { c: 'fa-solid fa-plug-circle-bolt', k: 'energia electricidad enchufe' },
      { c: 'fa-solid fa-lightbulb', k: 'luz bombilla electricidad' },
      { c: 'fa-solid fa-fire', k: 'gas fuego calefaccion servicio' },
      { c: 'fa-solid fa-fire-burner', k: 'estufa gas cocina' },
      { c: 'fa-solid fa-temperature-half', k: 'temperatura clima termostato' },
      { c: 'fa-solid fa-fan', k: 'ventilador aire hogar' },
      { c: 'fa-solid fa-wind', k: 'aire viento ventilacion' },
      { c: 'fa-solid fa-broom', k: 'escoba limpieza aseo hogar' },
      { c: 'fa-solid fa-soap', k: 'jabon limpieza aseo' },
      { c: 'fa-solid fa-trash-can', k: 'basura residuos aseo' },
      { c: 'fa-solid fa-wifi', k: 'internet wifi red servicio' },
      { c: 'fa-solid fa-tv', k: 'television tv entretenimiento' },
      { c: 'fa-solid fa-blender', k: 'licuadora electrodomestico cocina' },
      { c: 'fa-solid fa-kitchen-set', k: 'cocina utensilios hogar' },
      { c: 'fa-solid fa-wrench', k: 'herramienta reparacion mantenimiento' },
      { c: 'fa-solid fa-screwdriver-wrench', k: 'herramientas reparacion arreglo' },
      { c: 'fa-solid fa-hammer', k: 'martillo reparacion construccion' },
      { c: 'fa-solid fa-toolbox', k: 'caja herramientas reparacion' },
      { c: 'fa-solid fa-paint-roller', k: 'pintura rodillo remodelacion' },
      { c: 'fa-solid fa-trowel-bricks', k: 'construccion albanil ladrillo' },
      { c: 'fa-solid fa-plant-wilt', k: 'planta jardin hogar' },
    ],
  },
  {
    id: 'salud', label: 'Salud y bienestar', icon: 'fa-solid fa-heart-pulse',
    icons: [
      { c: 'fa-solid fa-heart-pulse', k: 'salud corazon pulso medico' },
      { c: 'fa-solid fa-heart', k: 'corazon amor salud' },
      { c: 'fa-solid fa-kit-medical', k: 'botiquin salud primeros auxilios' },
      { c: 'fa-solid fa-stethoscope', k: 'medico doctor salud consulta' },
      { c: 'fa-solid fa-user-doctor', k: 'doctor medico salud' },
      { c: 'fa-solid fa-pills', k: 'pastillas medicina farmacia' },
      { c: 'fa-solid fa-capsules', k: 'capsulas medicina farmacia' },
      { c: 'fa-solid fa-prescription-bottle-medical', k: 'medicina farmacia frasco' },
      { c: 'fa-solid fa-syringe', k: 'inyeccion vacuna medicina' },
      { c: 'fa-solid fa-tooth', k: 'diente dentista odontologia' },
      { c: 'fa-solid fa-eye', k: 'ojo vista oftalmologia' },
      { c: 'fa-solid fa-hospital', k: 'hospital clinica salud' },
      { c: 'fa-solid fa-notes-medical', k: 'historia medica salud examen' },
      { c: 'fa-solid fa-wheelchair', k: 'silla ruedas discapacidad' },
      { c: 'fa-solid fa-dumbbell', k: 'pesa gimnasio ejercicio fitness' },
      { c: 'fa-solid fa-person-running', k: 'correr ejercicio deporte' },
      { c: 'fa-solid fa-person-walking', k: 'caminar ejercicio' },
      { c: 'fa-solid fa-spa', k: 'spa relax bienestar' },
      { c: 'fa-solid fa-hand-holding-medical', k: 'salud cuidado ayuda' },
      { c: 'fa-solid fa-brain', k: 'cerebro mente psicologia' },
      { c: 'fa-solid fa-lungs', k: 'pulmones salud respirar' },
      { c: 'fa-solid fa-bone', k: 'hueso salud ortopedia' },
      { c: 'fa-solid fa-virus', k: 'virus enfermedad salud' },
    ],
  },
  {
    id: 'ocio', label: 'Ocio y entretenimiento', icon: 'fa-solid fa-gamepad',
    icons: [
      { c: 'fa-solid fa-gamepad', k: 'videojuego juego control gaming' },
      { c: 'fa-solid fa-dice', k: 'dado juego azar' },
      { c: 'fa-solid fa-dice-five', k: 'dado juego azar' },
      { c: 'fa-solid fa-chess-knight', k: 'ajedrez juego estrategia caballo' },
      { c: 'fa-solid fa-chess-king', k: 'ajedrez juego rey' },
      { c: 'fa-solid fa-puzzle-piece', k: 'rompecabezas juego puzzle' },
      { c: 'fa-solid fa-film', k: 'pelicula cine video' },
      { c: 'fa-solid fa-clapperboard', k: 'cine pelicula produccion' },
      { c: 'fa-solid fa-ticket', k: 'entrada boleto evento cine' },
      { c: 'fa-solid fa-masks-theater', k: 'teatro obra actuacion' },
      { c: 'fa-solid fa-music', k: 'musica cancion nota' },
      { c: 'fa-solid fa-headphones', k: 'audifonos musica audio' },
      { c: 'fa-solid fa-guitar', k: 'guitarra musica instrumento' },
      { c: 'fa-solid fa-drum', k: 'tambor bateria musica' },
      { c: 'fa-solid fa-microphone', k: 'microfono cantar musica' },
      { c: 'fa-solid fa-camera', k: 'camara foto fotografia' },
      { c: 'fa-solid fa-camera-retro', k: 'camara foto retro' },
      { c: 'fa-solid fa-video', k: 'video camara grabar' },
      { c: 'fa-solid fa-book', k: 'libro lectura estudio' },
      { c: 'fa-solid fa-palette', k: 'arte pintura color creatividad' },
      { c: 'fa-solid fa-paintbrush', k: 'pincel pintura arte' },
      { c: 'fa-solid fa-futbol', k: 'futbol balon deporte' },
      { c: 'fa-solid fa-basketball', k: 'baloncesto deporte' },
      { c: 'fa-solid fa-baseball', k: 'beisbol deporte pelota' },
      { c: 'fa-solid fa-volleyball', k: 'voleibol deporte pelota' },
      { c: 'fa-solid fa-table-tennis-paddle-ball', k: 'ping pong deporte' },
      { c: 'fa-solid fa-person-swimming', k: 'natacion nadar deporte' },
      { c: 'fa-solid fa-person-biking', k: 'ciclismo bici deporte' },
      { c: 'fa-solid fa-bowling-ball', k: 'bolos deporte juego' },
      { c: 'fa-solid fa-fire-flame-curved', k: 'fogata camping' },
      { c: 'fa-brands fa-spotify', k: 'spotify musica streaming' },
      { c: 'fa-brands fa-youtube', k: 'youtube video streaming' },
      { c: 'fa-brands fa-twitch', k: 'twitch streaming juego' },
      { c: 'fa-brands fa-playstation', k: 'playstation consola juego' },
      { c: 'fa-brands fa-xbox', k: 'xbox consola juego' },
      { c: 'fa-brands fa-steam', k: 'steam juegos gaming' },
      { c: 'fa-brands fa-nintendo-switch', k: 'nintendo switch consola' },
      { c: 'fa-brands fa-discord', k: 'discord chat juego comunidad' },
    ],
  },
  {
    id: 'educacion', label: 'Educación', icon: 'fa-solid fa-graduation-cap',
    icons: [
      { c: 'fa-solid fa-graduation-cap', k: 'graduacion estudio universidad educacion' },
      { c: 'fa-solid fa-book-open', k: 'libro abierto lectura estudio' },
      { c: 'fa-solid fa-book', k: 'libro lectura estudio' },
      { c: 'fa-solid fa-book-bookmark', k: 'libro marcador estudio' },
      { c: 'fa-solid fa-pen', k: 'lapiz escribir pluma' },
      { c: 'fa-solid fa-pencil', k: 'lapiz escribir dibujar' },
      { c: 'fa-solid fa-pen-ruler', k: 'diseno regla dibujo' },
      { c: 'fa-solid fa-ruler', k: 'regla medir dibujo' },
      { c: 'fa-solid fa-ruler-combined', k: 'regla escuadra medir' },
      { c: 'fa-solid fa-calculator', k: 'calculadora matematica numeros' },
      { c: 'fa-solid fa-flask', k: 'quimica laboratorio ciencia' },
      { c: 'fa-solid fa-flask-vial', k: 'quimica laboratorio experimento' },
      { c: 'fa-solid fa-microscope', k: 'microscopio ciencia laboratorio' },
      { c: 'fa-solid fa-atom', k: 'atomo ciencia fisica' },
      { c: 'fa-solid fa-dna', k: 'adn biologia ciencia' },
      { c: 'fa-solid fa-school', k: 'escuela colegio educacion' },
      { c: 'fa-solid fa-chalkboard', k: 'pizarra clase ensenanza' },
      { c: 'fa-solid fa-chalkboard-user', k: 'profesor clase ensenanza' },
      { c: 'fa-solid fa-language', k: 'idioma lenguaje traducir' },
      { c: 'fa-solid fa-globe', k: 'mundo geografia global' },
      { c: 'fa-solid fa-award', k: 'premio diploma logro' },
      { c: 'fa-solid fa-certificate', k: 'certificado diploma logro' },
      { c: 'fa-solid fa-backpack', k: 'mochila escuela estudiante' },
    ],
  },
  {
    id: 'personas', label: 'Personas y familia', icon: 'fa-solid fa-user',
    icons: [
      { c: 'fa-solid fa-user', k: 'usuario persona perfil' },
      { c: 'fa-solid fa-users', k: 'personas grupo familia' },
      { c: 'fa-solid fa-child', k: 'nino hijo familia' },
      { c: 'fa-solid fa-child-reaching', k: 'nino hijo jugar' },
      { c: 'fa-solid fa-baby', k: 'bebe hijo familia' },
      { c: 'fa-solid fa-person-breastfeeding', k: 'mama bebe familia' },
      { c: 'fa-solid fa-people-roof', k: 'familia hogar casa' },
      { c: 'fa-solid fa-user-group', k: 'grupo amigos personas' },
      { c: 'fa-solid fa-person-half-dress', k: 'persona pareja' },
      { c: 'fa-solid fa-hands-holding-child', k: 'cuidado nino familia' },
      { c: 'fa-solid fa-paw', k: 'mascota perro gato animal' },
      { c: 'fa-solid fa-dog', k: 'perro mascota animal' },
      { c: 'fa-solid fa-cat', k: 'gato mascota animal' },
      { c: 'fa-solid fa-fish-fins', k: 'pez mascota animal' },
      { c: 'fa-solid fa-crow', k: 'ave pajaro mascota' },
      { c: 'fa-solid fa-baby-carriage', k: 'coche bebe familia' },
      { c: 'fa-solid fa-cake-candles', k: 'cumpleanos fiesta celebracion' },
      { c: 'fa-solid fa-gift', k: 'regalo obsequio celebracion' },
      { c: 'fa-solid fa-ring', k: 'anillo boda matrimonio' },
      { c: 'fa-solid fa-heart', k: 'amor pareja corazon' },
      { c: 'fa-solid fa-people-arrows', k: 'personas intercambio compartir' },
      { c: 'fa-solid fa-person-cane', k: 'abuelo adulto mayor' },
    ],
  },
  {
    id: 'otros', label: 'Otros', icon: 'fa-solid fa-shapes',
    icons: [
      { c: 'fa-solid fa-star', k: 'estrella favorito destacado' },
      { c: 'fa-solid fa-bookmark', k: 'marcador guardar favorito' },
      { c: 'fa-solid fa-flag', k: 'bandera meta objetivo' },
      { c: 'fa-solid fa-bell', k: 'campana notificacion aviso' },
      { c: 'fa-solid fa-fire', k: 'fuego llama tendencia' },
      { c: 'fa-solid fa-bolt', k: 'rayo energia rapido' },
      { c: 'fa-solid fa-shield-halved', k: 'escudo seguro proteccion' },
      { c: 'fa-solid fa-lock', k: 'candado seguro privado' },
      { c: 'fa-solid fa-gear', k: 'engranaje ajuste configuracion' },
      { c: 'fa-solid fa-repeat', k: 'repetir recurrente suscripcion' },
      { c: 'fa-solid fa-rotate', k: 'ciclo recurrente actualizar' },
      { c: 'fa-solid fa-calendar-check', k: 'calendario fecha recurrente' },
      { c: 'fa-solid fa-hand-holding-heart', k: 'donacion caridad ayuda' },
      { c: 'fa-solid fa-hands-praying', k: 'oracion iglesia religion' },
      { c: 'fa-solid fa-church', k: 'iglesia religion' },
      { c: 'fa-solid fa-seedling', k: 'planta crecimiento naturaleza' },
      { c: 'fa-solid fa-leaf', k: 'hoja naturaleza eco' },
      { c: 'fa-solid fa-tree', k: 'arbol naturaleza planta' },
      { c: 'fa-solid fa-sun', k: 'sol clima dia' },
      { c: 'fa-solid fa-moon', k: 'luna noche clima' },
      { c: 'fa-solid fa-cloud', k: 'nube clima cielo' },
      { c: 'fa-solid fa-umbrella', k: 'paraguas lluvia clima' },
      { c: 'fa-solid fa-snowflake', k: 'nieve frio invierno' },
      { c: 'fa-solid fa-paw', k: 'mascota huella animal' },
      { c: 'fa-solid fa-recycle', k: 'reciclar eco ambiente' },
      { c: 'fa-solid fa-anchor', k: 'ancla mar barco' },
      { c: 'fa-solid fa-gift', k: 'regalo sorpresa' },
      { c: 'fa-solid fa-ellipsis', k: 'mas otro puntos varios' },
      { c: 'fa-solid fa-circle-question', k: 'pregunta duda otro' },
    ],
  },
];

// Lista plana de todas las clases (para búsquedas / validación)
export const ALL_ICONS = ICON_GROUPS.flatMap(g => g.icons);
